### ISSUE TITLE
Android 7.1 拍照崩溃

### ISSUE THREAD

**Issue by wangmy888** [jiangdongguo/AndroidUSBCamera#106]
E/ActivityManager: Sending non-protected broadcast android.net.ETHERNET_IFACE_REMOVED_ACTION from system 1113:system/1000 pkg android
                                                  java.lang.Throwable
                                                  at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:18244)
                                                      at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18845)
                                                      at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18936)
                                                      at android.app.ContextImpl.sendStickyBroadcast(ContextImpl.java:1150)
                                                      at com.android.server.ethernet.EthernetNetworkFactory.sendEthIfaceRemovedBroadcast(EthernetNetworkFactory.java:742)
                                                      at com.android.server.ethernet.EthernetNetworkFactory.-wrap3(EthernetNetworkFactory.java)
                                                      at com.android.server.ethernet.EthernetNetworkFactory$InterfaceObserver.interfaceRemoved(EthernetNetworkFactory.java:260)
                                                      at com.android.server.NetworkManagementService.notifyInterfaceRemoved(NetworkManagementService.java:454)
                                                      at com.android.server.NetworkManagementService.-wrap8(NetworkManagementService.java)
                                                      at com.android.server.NetworkManagementService$NetdCallbackReceiver.onEvent(NetworkManagementService.java:842)
                                                      at com.android.server.NativeDaemonConnector.handleMessage(NativeDaemonConnector.java:150)
                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                      at android.os.Looper.loop(Looper.java:154)
                                                      at android.os.HandlerThread.run(HandlerThread.java:61)
                                                      at com.android.server.ServiceThread.run(ServiceThread.java:46)

**Comment by quocnhat7** [comment]
If I am lib's creator, I will not reply for you because of this poor-words post.
