### ISSUE TITLE
Only one resolution works 

### ISSUE THREAD

**Issue by zipswich** [jiangdongguo/AndroidUSBCamera#340]
A USB camera has 11 resolutions, but only one (640x480) works.
I am using the demo app for testing.
The following is from logcat when the selected resolution (640x480) works:
```
07-27 09:39:50.460 1344-1344/com.jiangdg.usbcamera V/AbsUVCCameraHandler: close:
07-27 09:39:50.460 1344-1344/com.jiangdg.usbcamera V/AbsUVCCameraHandler: stopPreview:
07-27 09:39:50.461 1344-2409/com.jiangdg.usbcamera V/CameraThread: handleStopPreview:
07-27 09:39:50.512 316-921/? D/Gralloc: Allocate 20156416 Bytes cached memory via ion heap mask 1 successfully
07-27 09:39:50.574 1344-1344/com.jiangdg.usbcamera V/AbsUVCCameraHandler: stopPreview:finished
07-27 09:39:50.574 1344-2409/com.jiangdg.usbcamera V/CameraThread: handleStopPreview:finished
07-27 09:39:50.574 1344-1344/com.jiangdg.usbcamera V/AbsUVCCameraHandler: close:finished
07-27 09:39:50.574 1344-2409/com.jiangdg.usbcamera V/CameraThread: handleClose:
07-27 09:39:50.574 1344-2409/com.jiangdg.usbcamera V/UVCCameraTextureView: setVideoEncoder:
07-27 09:39:50.575 1344-1344/com.jiangdg.usbcamera V/CameraThread: getHandler:
07-27 09:39:50.576 1344-1420/com.jiangdg.usbcamera V/UVCCameraTextureView: RenderThread#setEncoder:encoder=null
07-27 09:39:50.577 1344-2409/com.jiangdg.usbcamera D/UsbDeviceConnectionJNI: close
07-27 09:39:50.582 1344-2610/com.jiangdg.usbcamera V/CameraThread: handleOpen:
07-27 09:39:50.582 1344-2610/com.jiangdg.usbcamera V/CameraThread: handleClose:
07-27 09:39:50.582 1344-2610/com.jiangdg.usbcamera V/UVCCameraTextureView: setVideoEncoder:
07-27 09:39:50.583 1344-1420/com.jiangdg.usbcamera V/UVCCameraTextureView: RenderThread#setEncoder:encoder=null
07-27 09:39:50.588 1344-2409/com.jiangdg.usbcamera V/CameraThread: handleRelease:mIsRecording=false
07-27 09:39:50.588 1344-2409/com.jiangdg.usbcamera V/CameraThread: handleClose:
07-27 09:39:50.588 1344-2409/com.jiangdg.usbcamera V/UVCCameraTextureView: setVideoEncoder:
07-27 09:39:50.588 1344-1420/com.jiangdg.usbcamera V/UVCCameraTextureView: RenderThread#setEncoder:encoder=null
07-27 09:39:50.588 1344-2409/com.jiangdg.usbcamera V/CameraThread: handleRelease:finished
07-27 09:39:50.599 1344-2610/com.jiangdg.usbcamera D/UsbDeviceConnectionJNI: close
07-27 09:39:50.600 1344-2610/com.jiangdg.usbcamera I/libusb/core: [2610*core.c:2085:libusb_init2]:libusb v1.0.19.10903
07-27 09:39:50.600 1344-2610/com.jiangdg.usbcamera I/libusb/usbfs: [2610*android_usbfs.c:504:op_init2]:start up hotplug event handler
07-27 09:39:50.600 1344-2610/com.jiangdg.usbcamera I/libusb/usbfs: [2610*android_usbfs.c:512:op_init2]:call android_scan_devices
07-27 09:39:50.602 1344-2610/com.jiangdg.usbcamera I/AbsUVCCameraHandler: supportedSize:{"formats":[{"index":1,"type":4,"default":1,"size":["3264x2448","2592x1944","2048x1536","1920x1080","1600x1200","1280x960","1280x720","1024x768","800x600","640x480","3264x2448"]},{"index":2,"type":6,"default":1,"size":["3264x2448","2592x1944","2048x1536","1920x1080","1600x1200","1280x960","1280x720","1024x768","800x600","640x480","3264x2448"]}]}
    
    --------- beginning of system
07-27 09:39:50.605 433-746/system_process W/InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@151b4efc attribute=null, token = android.os.BinderProxy@3fd1f627
07-27 09:39:51.093 1344-2611/com.jiangdg.usbcamera V/UVCCameraTextureView: getPreviewTexture:
07-27 09:39:51.093 1344-1420/com.jiangdg.usbcamera I/UVCCameraTextureView: RenderThread#updatePreviewSurface:
07-27 09:39:51.094 1344-1420/com.jiangdg.usbcamera D/UVCCameraTextureView: updatePreviewSurface:release mPreviewSurface
07-27 09:39:51.094 1344-1420/com.jiangdg.usbcamera V/UVCCameraTextureView: updatePreviewSurface:tex_id=490007
07-27 09:39:51.095 1344-2610/com.jiangdg.usbcamera V/CameraThread: handleStartPreview:
07-27 09:39:51.110 1344-2610/com.jiangdg.usbcamera I/libUVCCamera: [2610*UVCPreview.cpp:276:callbackPixelFormatChanged]:PIXEL_FORMAT_YUV20SP:
07-27 09:39:51.167 1344-2619/com.jiangdg.usbcamera I/libUVCCamera: [2619*UVCPreview.cpp:492:prepare_preview]:frameSize=(640,480)@MJPEG
07-27 09:39:51.178 1344-2620/com.jiangdg.usbcamera W/libUVCCamera: [2620*UVCPreview.cpp:119:get_frame]:allocate new frame
07-27 09:39:51.178 1344-2619/com.jiangdg.usbcamera W/libUVCCamera: [2619*UVCPreview.cpp:119:get_frame]:allocate new frame
07-27 09:39:51.179 1344-2621/com.jiangdg.usbcamera I/libUVCCamera: [2621*UVCPreview.cpp:276:callbackPixelFormatChanged]:PIXEL_FORMAT_YUV20SP:
07-27 09:39:51.203 316-921/? D/Gralloc: Allocate 1228800 Bytes cached memory via ion heap mask 1 successfully
07-27 09:39:51.208 1344-2620/com.jiangdg.usbcamera W/libUVCCamera: [2620*UVCPreview.cpp:119:get_frame]:allocate new frame
07-27 09:39:51.212 1344-2621/com.jiangdg.usbcamera W/libUVCCamera: [2621*UVCPreview.cpp:119:get_frame]:allocate new frame
07-27 09:39:51.221 1344-2621/com.jiangdg.usbcamera D/Debug: onPreviewResult: 460800
07-27 09:39:51.266 316-852/? D/Gralloc: Allocate 1228800 Bytes cached memory via ion heap mask 1 successfully
07-27 09:39:51.281 1344-2621/com.jiangdg.usbcamera D/Debug: onPreviewResult: 460800
07-27 09:39:51.299 316-921/? D/Gralloc: Allocate 1228800 Bytes cached memory via ion heap mask 1 successfully
07-27 09:39:51.314 1344-2621/com.jiangdg.usbcamera D/Debug: onPreviewResult: 460800
07-27 09:39:51.342 1344-2621/com.jiangdg.usbcamera D/Debug: onPreviewResult: 460800
07-27 09:39:51.376 1344-2621/com.jiangdg.usbcamera D/Debug: onPreviewResult: 460800
07-27 09:39:51.415 1344-2621/com.jiangdg.usbcamera D/Debug: onPreviewResult: 460800
```

The following is from logcat when the selected resolution does not work (i.e. preview is black):
```
07-27 15:49:00.351 1344-1344/com.jiangdg.usbcamera V/AbsUVCCameraHandler: close:
07-27 15:49:00.351 1344-1344/com.jiangdg.usbcamera V/AbsUVCCameraHandler: stopPreview:
07-27 15:49:00.352 1344-8208/com.jiangdg.usbcamera V/CameraThread: handleStopPreview:
07-27 15:49:00.361 1344-8222/com.jiangdg.usbcamera D/Debug: onPreviewResult: 460800
07-27 15:49:00.416 1344-1344/com.jiangdg.usbcamera V/AbsUVCCameraHandler: stopPreview:finished
07-27 15:49:00.416 1344-8208/com.jiangdg.usbcamera V/CameraThread: handleStopPreview:finished
07-27 15:49:00.416 1344-1344/com.jiangdg.usbcamera V/AbsUVCCameraHandler: close:finished
07-27 15:49:00.416 1344-8208/com.jiangdg.usbcamera V/CameraThread: handleClose:
07-27 15:49:00.416 1344-8208/com.jiangdg.usbcamera V/UVCCameraTextureView: setVideoEncoder:
07-27 15:49:00.418 1344-1344/com.jiangdg.usbcamera V/CameraThread: getHandler:
07-27 15:49:00.418 1344-7993/com.jiangdg.usbcamera V/UVCCameraTextureView: RenderThread#setEncoder:encoder=null
07-27 15:49:00.422 1344-8208/com.jiangdg.usbcamera D/UsbDeviceConnectionJNI: close
07-27 15:49:00.423 1344-8335/com.jiangdg.usbcamera V/CameraThread: handleOpen:
07-27 15:49:00.423 1344-8335/com.jiangdg.usbcamera V/CameraThread: handleClose:
07-27 15:49:00.423 1344-8335/com.jiangdg.usbcamera V/UVCCameraTextureView: setVideoEncoder:
07-27 15:49:00.424 1344-7993/com.jiangdg.usbcamera V/UVCCameraTextureView: RenderThread#setEncoder:encoder=null
07-27 15:49:00.428 1344-8208/com.jiangdg.usbcamera V/CameraThread: handleRelease:mIsRecording=false
07-27 15:49:00.429 1344-8208/com.jiangdg.usbcamera V/CameraThread: handleClose:
07-27 15:49:00.429 1344-8208/com.jiangdg.usbcamera V/UVCCameraTextureView: setVideoEncoder:
07-27 15:49:00.429 1344-7993/com.jiangdg.usbcamera V/UVCCameraTextureView: RenderThread#setEncoder:encoder=null
07-27 15:49:00.429 1344-8208/com.jiangdg.usbcamera V/CameraThread: handleRelease:finished
07-27 15:49:00.434 1344-8335/com.jiangdg.usbcamera D/UsbDeviceConnectionJNI: close
07-27 15:49:00.434 1344-8335/com.jiangdg.usbcamera I/libusb/core: [8335*core.c:2085:libusb_init2]:libusb v1.0.19.10903
07-27 15:49:00.434 1344-8335/com.jiangdg.usbcamera I/libusb/usbfs: [8335*android_usbfs.c:504:op_init2]:start up hotplug event handler
07-27 15:49:00.435 1344-8335/com.jiangdg.usbcamera I/libusb/usbfs: [8335*android_usbfs.c:512:op_init2]:call android_scan_devices
07-27 15:49:00.436 1344-8335/com.jiangdg.usbcamera I/AbsUVCCameraHandler: supportedSize:{"formats":[{"index":1,"type":4,"default":1,"size":["3264x2448","2592x1944","2048x1536","1920x1080","1600x1200","1280x960","1280x720","1024x768","800x600","640x480","3264x2448"]},{"index":2,"type":6,"default":1,"size":["3264x2448","2592x1944","2048x1536","1920x1080","1600x1200","1280x960","1280x720","1024x768","800x600","640x480","3264x2448"]}]}
    
    --------- beginning of system
07-27 15:49:00.446 433-458/system_process W/InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@105b3fd attribute=null, token = android.os.BinderProxy@16e6f306
07-27 15:49:00.928 1344-8336/com.jiangdg.usbcamera V/UVCCameraTextureView: getPreviewTexture:
07-27 15:49:00.929 1344-7993/com.jiangdg.usbcamera I/UVCCameraTextureView: RenderThread#updatePreviewSurface:
07-27 15:49:00.929 1344-7993/com.jiangdg.usbcamera D/UVCCameraTextureView: updatePreviewSurface:release mPreviewSurface
07-27 15:49:00.930 1344-7993/com.jiangdg.usbcamera V/UVCCameraTextureView: updatePreviewSurface:tex_id=350005
07-27 15:49:00.934 1344-8335/com.jiangdg.usbcamera V/CameraThread: handleStartPreview:
07-27 15:49:00.969 1344-8335/com.jiangdg.usbcamera I/libUVCCamera: [8335*UVCPreview.cpp:276:callbackPixelFormatChanged]:PIXEL_FORMAT_YUV20SP:
07-27 15:49:01.004 1344-8352/com.jiangdg.usbcamera I/libUVCCamera: [8352*UVCPreview.cpp:492:prepare_preview]:frameSize=(3264,2448)@MJPEG
07-27 15:49:01.018 1344-8354/com.jiangdg.usbcamera W/libUVCCamera: [8354*UVCPreview.cpp:119:get_frame]:allocate new frame
07-27 15:49:01.018 1344-8355/com.jiangdg.usbcamera I/libUVCCamera: [8355*UVCPreview.cpp:276:callbackPixelFormatChanged]:PIXEL_FORMAT_YUV20SP:
07-27 15:49:01.019 1344-8352/com.jiangdg.usbcamera W/libUVCCamera: [8352*UVCPreview.cpp:119:get_frame]:allocate new frame
07-27 15:49:02.431 1344-1367/com.jiangdg.usbcamera W/MessageQueue: Handler (android.os.Handler) {2dbfe12f} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {2dbfe12f} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
        at android.os.Handler.enqueueMessage(Handler.java:631)
        at android.os.Handler.sendMessageAtTime(Handler.java:600)
        at android.os.Handler.sendMessageDelayed(Handler.java:570)
        at android.os.Handler.post(Handler.java:326)
        at android.widget.Toast$TN.hide(Toast.java:387)
        at android.app.ITransientNotification$Stub.onTransact(ITransientNotification.java:55)
        at android.os.Binder.execTransact(Binder.java:446)
```

Could anyone shed some light on this?

**Comment by zipswich** [comment]
I have just found out that other resolutions will work if I unplug and re-plug the camera **after** selecting a new resolution.   In this case, the app will ask for camera access permission again.

**Comment by jiangdongguo** [comment]
Please update to new (3.0), and have a try.
