### ISSUE TITLE
3.2.8使用过程中偶尔出现USBMonitor  already destroyed，请问什么原因

### ISSUE THREAD

**Issue by liu408309046** [jiangdongguo/AndroidUSBCamera#456]
平时正常预览拍照，只是偶然会出现这个问题导致闪退，请问是什么原因导致

java.lang.IllegalStateException: already destroyed
	at com.serenegiant.usb.USBMonitor.hasPermission(USBMonitor.java:400)
	at com.serenegiant.usb.USBMonitor$2.run(USBMonitor.java:554)
	at android.os.Handler.handleCallback(Handler.java:755)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by jiangdongguo** [comment]
是不是跟你的使用逻辑有关系，看日志相似摄像头销毁了，你还去判断是否有权限
