### ISSUE TITLE
修改了UVCPreview.cpp 的代码，重新编译app，app启动后一直报错，进不去主页面

### ISSUE THREAD

**Issue by jackandroid2016** [jiangdongguo/AndroidUSBCamera#482]
修改了UVCPreview.cpp 的代码，重新编译app，app启动后一直报错，进不去主页面，下边是日志信息

Time：2022-10-27 13:37:32:930
VersionInfo：versionCode=121 versionName：3.2.10
PhoneInfo  ：manufacture=KTE model=L10
SystemInfo ：version=7.1.1
java.lang.UnsatisfiedLinkError: dlopen failed: file offset for the library "/data/app/com.jiangdg.ausbc-1/lib/arm64/libjpeg-turbo1500.so" >= file size: 0 >= 0
	at java.lang.Runtime.loadLibrary0(Runtime.java:989)
	at java.lang.System.loadLibrary(System.java:1530)
	at com.jiangdg.uvc.UVCCamera.<clinit>(UVCCamera.java:120)
	at com.jiangdg.ausbc.CameraClient$Builder.openDebug(CameraClient.kt:718)
	at com.jiangdg.demo.DemoFragment.getCameraClient(DemoFragment.kt:182)
	at com.jiangdg.ausbc.base.CameraFragment.initData(CameraFragment.kt:48)
	at com.jiangdg.demo.DemoFragment.initData(DemoFragment.kt:195)
	at com.jiangdg.ausbc.base.BaseFragment.onViewCreated(BaseFragment.kt:45)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
	at com.jiangdg.demo.MainActivity.onStart(MainActivity.kt:51)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
	at android.app.Activity.performStart(Activity.java:6698)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2706)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
End=====================================

**Comment by jiangdongguo** [comment]
java.lang.UnsatisfiedLinkError: dlopen failed: file offset for the library "/data/app/com.jiangdg.ausbc-1/lib/arm64/libjpeg-turbo1500.so" >= file size: 0 >= 0    编译异常了吧？
