### ISSUE TITLE
发生崩溃

### ISSUE THREAD

**Issue by yuanmaio** [jiangdongguo/AndroidUSBCamera#497]
native: #35 pc 00000000000500d0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
    runtime.cc:655]   at com.serenegiant.usb.UVCCamera.nativeStopPreview(Native method)
    runtime.cc:655]   at com.serenegiant.usb.UVCCamera.stopPreview(UVCCamera.java:447)
    runtime.cc:655]   - locked <0x01dabab1> (a com.serenegiant.usb.UVCCamera)
    runtime.cc:655]   at com.serenegiant.usb.common.AbstractUVCCameraHandler$CameraThread.handleStopPreview(AbstractUVCCameraHandler.java:581)
    runtime.cc:655]   at com.serenegiant.usb.common.AbstractUVCCameraHandler.handleMessage(AbstractUVCCameraHandler.java:368)
    runtime.cc:655]   at android.os.Handler.dispatchMessage(Handler.java:106)
    runtime.cc:655]   at android.os.Looper.loop(Looper.java:223)
    runtime.cc:655]   at com.serenegiant.usb.common.AbstractUVCCameraHandler$CameraThread.run(AbstractUVCCameraHandler.java:1109)
    runtime.cc:655] 
    runtime.cc:655] "RenderThread" prio=5 tid=134 Native
    runtime.cc:655]   | group="" sCount=1 dsCount=0 flags=1 obj=0x133c0170 self=0x7dc4a5add0
    runtime.cc:655]   | sysTid=15805 nice=0 cgrp=default sched=0/0 handle=0x7b9d829cc0
    runtime.cc:655]   | state=S schedstat=( 2270185985 151529271 3062 ) utm=173 stm=53 core=2 HZ=100
    runtime.cc:655]   | stack=0x7b9d726000-0x7b9d728000 stackSize=1043KB
    runtime.cc:655]   | held mutexes=
    runtime.cc:655]   native: #00 pc 000000000009b998  /apex/com.android.runtime/lib64/bionic/libc.so (__epoll_pwait+8)
    runtime.cc:655]   native: #01 pc 0000000000019a2c  /system/lib64/libutils.so (android::Looper::pollInner(int)+184)
    runtime.cc:655]   native: #02 pc 000000000001990c  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112)
    runtime.cc:655]   native: #03 pc 0000000000110e1c  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
    runtime.cc:655]   at android.os.MessageQueue.nativePollOnce(Native method)
    runtime.cc:655]   at android.os.MessageQueue.next(MessageQueue.java:335)
    runtime.cc:655]   at android.os.Looper.loop(Looper.java:183)
    runtime.cc:655]   at com.serenegiant.usb.widget.UVCCameraTextureView$RenderHandler$RenderThread.run(UVCCameraTextureView.java:553)
    runtime.cc:655] 
    runtime.cc:655] "arch_disk_io_3" prio=5 tid=138 Waiting
    runtime.cc:655]   | group="" sCount=1 dsCount=0 flags=1 obj=0x133c0b50 self=0x7dc4a60140
    runtime.cc:655]   | sysTid=15830 nice=0 cgrp=default sched=0/0 handle=0x7b2817fcc0
    runtime.cc:655]   | state=S schedstat=( 6893540 0 2 ) utm=0 stm=0 core=4 HZ=100
    runtime.cc:655]   | stack=0x7b2807c000-0x7b2807e000 stackSize=1043KB
    runtime.cc:655]   | held mutexes=
    runtime.cc:655]   native: #00 pc 000000000004b20c  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
    runtime.cc:655]   native: #01 pc 00000000005969f0  /apex/com.android.art/lib64/libart.so (art::Thread::Park(bool, long)+444)
    runtime.cc:655]   native: #02 pc 00000000004d287c  /apex/com.android.art/lib64/libart.so (art::Unsafe_park(_JNIEnv*, _jobject*, unsigned char, long)+640)
    runtime.cc:655]   at sun.misc.Unsafe.park(Native method)
    runtime.cc:655]   - waiting on an unknown object
    runtime.cc:655]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
    runtime.cc:655]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
    runtime.cc:655]   at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
    runtime.cc:655]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
    runtime.cc:655]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
    runtime.cc:655]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    runtime.cc:655]   at java.lang.Thread.run(Thread.java:923)
    runtime.cc:655] 
    runtime.cc:655] Aborting thread:
    runtime.cc:655] "Thread-170" prio=5 tid=130 Native
    runtime.cc:655]   | group="" sCount=0 dsCount=0 flags=0 obj=0x133c0280 self=0x7dc4a522c0

**Comment by yuanmaio** [comment]
求大佬指点解决方法啊
