### ISSUE TITLE
调用stopPreview有一定几率出现ANR错误

### ISSUE THREAD

**Issue by 2284990886** [jiangdongguo/AndroidUSBCamera#502]
猜测是调用stopPreview是，线程暂停之后没有收到通知，然后出现ANR
下面是ANR原文:
DALVIK THREADS (52):
"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x74038b18 self=0xb80e50f0
  | sysTid=3041 nice=0 cgrp=default sched=0/0 handle=0xb6f0fbec
  | state=S schedstat=( 198273541982 258716532640 250688 ) utm=13636 stm=6191 core=3 HZ=100
  | stack=0xbe1aa000-0xbe1ac000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x3a9a8f22> (a java.lang.Object)
  at com.serenegiant.usb.common.AbstractUVCCameraHandler.stopPreview(AbstractUVCCameraHandler.java:234)
  - locked <0x3a9a8f22> (a java.lang.Object)
  at com.jiangdg.usbcamera.UVCCameraHelper.stopPreview(UVCCameraHelper.java:354)
  at com.xngz.table.camera.CameraActivity.onSurfaceDestroy(CameraActivity.java:455)
  at com.serenegiant.usb.widget.UVCCameraTextureView.onSurfaceTextureDestroyed(UVCCameraTextureView.java:139)
  at android.view.TextureView.destroySurface(TextureView.java:237)
  at android.view.TextureView.destroyHardwareResources(TextureView.java:342)
  at android.view.ThreadedRenderer.destroyResources(ThreadedRenderer.java:170)
  at android.view.ThreadedRenderer.destroyResources(ThreadedRenderer.java:177)
  at android.view.ThreadedRenderer.destroyResources(ThreadedRenderer.java:177)
  at android.view.ThreadedRenderer.destroyResources(ThreadedRenderer.java:177)
  ... repeated 2 times
  at android.view.ThreadedRenderer.destroyHardwareResources(ThreadedRenderer.java:165)
  at android.view.ViewRootImpl.destroyHardwareResources(ViewRootImpl.java:666)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1332)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1073)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5903)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:773)
  at android.view.Choreographer.doCallbacks(Choreographer.java:586)
  at android.view.Choreographer.doFrame(Choreographer.java:556)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5254)
  at java.lang.reflect.Method.invoke!(Native method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)

**Comment by jiangdongguo** [comment]
哪个版本？试试3.3.2
