### ISSUE TITLE
3.3.3 版本 出现 OutOfMemoryError

### ISSUE THREAD

**Issue by loadmore** [jiangdongguo/AndroidUSBCamera#592]
3.3.3 版本 出现 OutOfMemoryError

java.lang.OutOfMemoryError: Could not allocate JNI Envat java.lang.Thread.nativeCreate(Native Method)
at java.lang.Thread.start(Thread.java:730)at com.ianqdq.ausbc.render.RenderManager.startRenderScreen(RenderManager.kt:251)at comjiangdq.ausbc.MultiCameraClientSICamera.handleMessage(MultiCameraClient.kt:326)at android.os.Handler.dispatchMessage(Handlerjava:98)at android.os.Looper.loop(Looperjava:154)at android.os.HandlerThread.run(HandlerThread.java:61)
![WechatIMG3383](https://github.com/jiangdongguo/AndroidUSBCamera/assets/46996582/d16cd982-c602-4894-aac5-b82bad523e18)

**Comment by loadmore** [comment]
Process: com.worker.robot, PID: 25269
                                                                             java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
                                                                             	at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
                                                                             	at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:244)
                                                                             	at com.jiangdg.ausbc.render.RenderManager.handleMessage(RenderManager.kt:161)
                                                                             	at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                             	at android.os.Looper.loop(Looper.java:154)
                                                                             	at android.os.HandlerThread.run(HandlerThread.java:61)
