### ISSUE TITLE
[Mp4Muxer]  release media muxer failed, err = Failed to stop the muxer

### ISSUE THREAD

**Issue by hjunren** [jiangdongguo/AndroidUSBCamera#602]
023-09-15 18:20:52.407 4844-685/com.jiangdg.ausbc I/AUSBC: [H264EncodeProcessor]  init h264 media codec success, bit = 
2023-09-15 18:20:52.411 4844-345/com.jiangdg.ausbc E/AUSBC: [Mp4Muxer]  release media muxer failed, err = Failed to stop the muxer
2023-09-15 18:20:52.411 4844-345/com.jiangdg.ausbc E/AUSBC: java.lang.IllegalStateException: Failed to stop the muxer
2023-09-15 18:20:52.411 4844-345/com.jiangdg.ausbc E/AUSBC:     at android.media.MediaMuxer.nativeStop(Native Method)
2023-09-15 18:20:52.411 4844-345/com.jiangdg.ausbc E/AUSBC:     at android.media.MediaMuxer.stop(MediaMuxer.java:466)
2023-09-15 18:20:52.411 4844-345/com.jiangdg.ausbc E/AUSBC:     at com.jiangdg.ausbc.encode.muxer.Mp4Muxer.release(Mp4Muxer.kt:224)
2023-09-15 18:20:52.411 4844-345/com.jiangdg.ausbc E/AUSBC:     at com.jiangdg.ausbc.MultiCameraClient$ICamera.captureVideoStopInternal(MultiCameraClient.kt:876)
2023-09-15 18:20:52.411 4844-345/com.jiangdg.ausbc E/AUSBC:     at com.jiangdg.ausbc.MultiCameraClient$ICamera.handleMessage(MultiCameraClient.kt:374)
2023-09-15 18:20:52.411 4844-345/com.jiangdg.ausbc E/AUSBC:     at android.os.Handler.dispatchMessage(Handler.java:103)
2023-09-15 18:20:52.411 4844-345/com.jiangdg.ausbc E/AUSBC:     at android.os.Looper.loop(Looper.java:214)
2023-09-15 18:20:52.411 4844-345/com.jiangdg.ausbc E/AUSBC:     at android.os.HandlerThread.run(HandlerThread.java:67)
2023-09-15 18:20:52.414 4844-345/com.jiangdg.ausbc I/AUSBC: [MultiCameraClient]  capturing video stop

用demo录制的视频，点击结束的时候报错

**Comment by hjunren** [comment]
![image](https://github.com/jiangdongguo/AndroidUSBCamera/assets/16415545/a53a81ee-5276-4854-8e96-5c59a2c55ece)
![image](https://github.com/jiangdongguo/AndroidUSBCamera/assets/16415545/06099f78-be79-4dc8-a7d2-7058458ac9fb)
这样修改后，错误消失了
