### ISSUE TITLE
频繁开关摄像头存在anr问题，怀疑是死锁造成的

### ISSUE THREAD

**Issue by unengchen** [jiangdongguo/AndroidUSBCamera#637]
这是跟框架有关的日志  
at com.jiangdg.uvc.UVCCamera.nativeRelease(Native method)
  at com.jiangdg.uvc.UVCCamera.close(UVCCamera.java:261)
  - locked <0x0f6ba351> (a com.jiangdg.uvc.UVCCamera)
  at com.zcla.usbcamera.UsbCameraManager.closeCamera(UsbCameraManager.kt:112)
  at com.zcla.gunbulletcabinet.activity.auth.AuthFaceActivity.onPause(AuthFaceActivity.kt:92)

以下是完整日志：
[anr_2024-01-24-11-03-34-683.zip](https://github.com/jiangdongguo/AndroidUSBCamera/files/14032194/anr_2024-01-24-11-03-34-683.zip)

**Comment by CandyTek** [comment]
我也发现了，这种情况应该怎么解决

**Comment by CaoXiLin** [comment]
怎么解决了
